### ISSUE TITLE
Check data files used by tests into GitHub repository

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/VAPr#10]
As of 07/14/2017, 14 unit tests are failing due to expected test files not being included in the repository.  Please check in:

VAPr/test_files/design_file_by_dir_name.csv
/Volumes/Carlo_HD1/CCBB/VAPr_files/design_file_three_samples.csv
VAPr/test_files/annotated.hg19_multianno.txt

... and any other files that these three files reference that are necessary for the tests to run.

**Comment by kmfisch** [comment]
@AmandaBirmingham please close this issue once this has been fixed
