### ISSUE TITLE
Optimize performance -- query myvariant.info for union of all sample variants

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/VAPr#12]
Take the union of all samples and annotate these as one batch with myvariant.info to speed up query

**Comment by AmandaBirmingham** [comment]
All samples are now aggregated into a single vcf that is subsequently mined for variants to annotate: https://github.com/ucsd-ccbb/VAPr/blob/133d0ab51796d882d4de39152c8ca26535513a0c/VAPr/vapr_core.py#L248
