### ISSUE TITLE
Create write csv function after myvariant.info annotation before loading into mongodb  as intermediate output

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/VAPr#14]
Create a function to write a csv sample for all annotated variants (annovar and myvariant.info) per sample and/or all samples (include this option) before loading into mongodb rather than after.

**Comment by AmandaBirmingham** [comment]
@kmfisch Why?  I don't understand the use-case for this proposed change.

**Comment by kmfisch** [comment]
This issue is now deprecated. :)
