### ISSUE TITLE
Design File Configuration

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/VAPr#2]
Make columns user-defined (except Sample_Name) and write them into the MongoDB documents for each sample/variant.

**Comment by carlomazzaferro** [comment]
Fixed by 673412ba47ffae689a43bf279f367fe3cf5f7c40

**Comment by carlomazzaferro** [comment]
Tests added d071cb1c7647b1c21982fff209a3c456ee1bd521
