### ISSUE TITLE
Update documentation and post to Read The Docs

### ISSUE THREAD

**Issue by carlomazzaferro** [ucsd-ccbb/VAPr#22]
Created new branch `docs_develop` where documentation to be posted on RTD is being written. Some notes: 

To enable automatic builds every time commits appear a webhook needs to be set up:  
 
- Go to the Settings page for your github project 
- Click Webhooks and then Add webhook
- For Payload URL, use readthedocs.org/api/v2/webhook/vapr/8271/
- For Content type, both application/json and application/x-www-form-urlencoded work
- Select Just the push event
- Finish by clicking Add webhook
 
From: https://docs.readthedocs.io/en/latest/webhooks.html#webhook-creation

I'll be parsing info from the README to docstrings along this week, using numpy-style docstrings:
http://www.sphinx-doc.org/en/stable/ext/example_numpy.html (unless some other is preferred)

**Comment by AmandaBirmingham** [comment]
Thanks!  Please use Google-style docstrings, which Is CCBB’s chosen format standard :) (see http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html )
Amanda
